accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from accounts.views import signup

# from accounts.views import SignUpView

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
    # path("signup/", SignUpView.as_view(), name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCategoryCreateView,
    AccountCreateView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/", ExpenseCategoryListView.as_view(), name="category_list"
    ),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

# Create your models here.

USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/views.py
from django.shortcuts import render, redirect

# Create your views here.

from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username, password=password
            )
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()

    context = {"form": form}
    return render(request, "registration/signup.html", context)


# from django.views.generic.edit import CreateView
# from django.urls import reverse_lazy


# class SignUpView(CreateView):
#     form_class = UserCreationForm
#     success_url = reverse_lazy("home")
#     template_name = "registration/signup.html"

receipts/views.py
from django.shortcuts import render, redirect

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from receipts.models import Receipt, Account, ExpenseCategory
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/new.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    # success_url = reverse_lazy("home")

    def form_valid(self, form):
        receipt = form.save(commit=False)
        receipt.purchaser = self.request.user
        receipt.save()
        return redirect("home")

    # below function allow user to see categories and accounts CREATED BY USER ONLY
    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, *kwargs)
        form.fields["category"].queryset = self.request.user.categories.all()
        form.fields["account"].queryset = self.request.user.accounts.all()
        return form


# Receipt createview in functions
# def create_receipt(request):
#     if request.method == “POST”:
#         form = ReceiptForm(request.POST)
#         if form.is_valid():
#             receipt = form.instance
#             receipt.purchaser = request.user
#             receipt.save()
#             return redirect(“home”)
#     else:
#         form = ReceiptForm()
#         form.fields[“category”].queryset = request.user.categories.all()
#         form.fields[“account”].queryset = request.user.accounts.all()
#     context = {“form”: form}
#     return render(request, “receipts/new_receipt.html”, context)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/category_list.html"
    # context_object_name = "expensecategory_list"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/account_list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/newcategory.html"
    fields = ["name"]

    def form_valid(self, form):
        category = form.save(commit=False)
        category.owner = self.request.user
        category.save()
        return redirect("category_list")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/newaccount.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        account = form.save(commit=False)
        account.owner = self.request.user
        account.save()
        return redirect("account_list")

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
    <title>My Receipts</title>
    {% endblock title %}
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'home' %}">Home</a>
          </li>
          <li>
            <a href="{% url 'create_receipt' %}">Create Receipt</a>
          </li>
          <li>
            <a href="{% url 'category_list' %}">Expense Category List</a>
          </li>
          <li>
            <a href="{% url 'create_category' %}">Create Category</a>
          </li>
          <li>
            <a href="{% url 'account_list' %}">Account List</a>
          </li>
          <li>
            <a href="{% url 'create_account' %}">Create Account</a>
          </li>
          <li>
            <a href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
            <a href="{% url 'signup' %}">Signup</a>
          </li>
          <li>
            <a href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>{% block content %} {% endblock content %}</main>
  </body>
</html>

receipts/templates/receipts/account_list.html
{% extends 'base.html' %} {% block title %}
<title>Account List</title>
{% endblock title %} {% block content %}

<h1>Account List</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Number of receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for account in account_list %}
    <tr>
      <td>{{ account.name }}</td>
      <td>{{ account.number }}</td>
      <td>{{ account.receipts.all|length }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

receipts/templates/receipts/category_list.html
{% extends 'base.html' %} {% block title %}
<title>Category List</title>
{% endblock title %} {% block content %}

<h1>Expense Category List</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for category in expensecategory_list %}
    <tr>
      <td>{{ category.name }}</td>
      <td>{{ category.receipts.all|length }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %} {% block title %}
<title>Receipts</title>
{% endblock title %} {% block content %}

<h1>My Receipts</h1>
<table>
  <thead>
    <tr>
      <th>Vendor</th>
      <th>Total</th>
      <th>Tax</th>
      <th>Date</th>
      <th>Category</th>
      <th>Account</th>
    </tr>
  </thead>
  <tbody>
    {% for receipt in receipt_list %}
    <tr>
      <td>{{ receipt.vendor }}</td>
      <td>{{ receipt.total }}</td>
      <td>{{ receipt.tax }}</td>
      <td>{{ receipt.date }}</td>
      <td>{{ receipt.category }}</td>
      <td>{{ receipt.account }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

receipts/templates/receipts/new.html
{% extends 'base.html' %} {% block title %}
<title>Create Receipt</title>
{% endblock title %} {% block content %}

<div>
  <h1>Create Recipt</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button>Create</button>
  </form>
</div>

{% endblock content %}

receipts/templates/receipts/newaccount.html
{% extends 'base.html' %} {% block title %}
<title>Create Account</title>
{% endblock title %} {% block content %}

<div>
  <h1>Create Account</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button>Create</button>
  </form>
</div>

{% endblock content %}

receipts/templates/receipts/newcategory.html
{% extends 'base.html' %} {% block title %}
<title>Create Category</title>
{% endblock title %} {% block content %}

<div>
  <h1>Create Category</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button>Create</button>
  </form>
</div>

{% endblock content %}